[package]
name = "xlxsbuilder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_xlsxwriter = "0.70.0"
serde = "1.0.204"
serde_json = "1.0.120"